config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  use_doorkeeper
  devise_for :authors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Sets the root page to be the login of devise
  devise_scope :author do
    root "devise/sessions#new"
  end
  
  resources :authors do
    resources :posts do
      resources :comments
      resources :likes, only: [:create, :destroy]
    end
  end

  
  # API ROUTES
  namespace :api do # /api
    namespace :v1 do # /api/v1
      resources :authors do # api/v1/users
        resources :posts, format: :json do # api/v1/users/:user_id/posts
          resources :comments, format: :json # api/v1/users/:user_id/posts/:post_id/comments
        end
      end
    end
  end

  scope :api do
    scope :v1 do
      use_doorkeeper do
        skip_controllers :authorizations, :applications, :authorized_applications
      end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  after_save :update_comments_counter

  belongs_to :author
  belongs_to :post

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::ApplicationController
  def create
    comment = Comment.new(comment_params)
    if comment.save
      render json: comment, status: :created
    else
      render json: comment.errors, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params
      .require(:comment)
      .permit(:text)
      .with_defaults(author_id: current_author.id, post_id: params[:post_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(comment_params)
    if comment.save
      redirect_back_or_to author_post_path(current_author, params[:post_id]),
                          notice: 'Comment was successfully created.'
    else
      redirect_back_or_to author_post_path(current_author, params[:post_id]), notice: 'Error creating the comment.'
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    respond_to do |format|
      format.html do
        redirect_back_or_to author_post_path(current_author, params[:post_id]),
                            notice: 'Comment was successfully deleted.'
      end
    end
  end

  private

  def comment_params
    params
      .require(:comment)
      .permit(:text)
      .with_defaults(author_id: current_author.id, post_id: params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <img src="https://picsum.photos/200" />
  <div class="author-comment">
    <h4><%= comment.author.name %></h4>
    <p><%= comment.text %></p>
  </div>
  <% if can? :destroy, comment %>
    <%= form_with model: comment, url: author_post_comment_path(comment.author, comment.post, comment), method: :delete do |form| %>
      <%= form.submit "x", class: "btn" %>
    <% end %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @post.author, @post, @post.comments.build ], class: 'comment-form' do |form| %>
  <%= form.label :text %>
  <%= form.text_field :text, class: 'comment-input', placeholder: "Write a comment..." %>
  <%= form.submit "Comment", class: 'btn' %>
<% end %>