config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  use_doorkeeper
  devise_for :authors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Sets the root page to be the login of devise
  devise_scope :author do
    root "devise/sessions#new"
  end
  
  resources :authors do
    resources :posts do
      resources :comments
      resources :likes, only: [:create, :destroy]
    end
  end

  
  # API ROUTES
  namespace :api do # /api
    namespace :v1 do # /api/v1
      resources :authors do # api/v1/users
        resources :posts, format: :json do # api/v1/users/:user_id/posts
          resources :comments, format: :json # api/v1/users/:user_id/posts/:post_id/comments
        end
      end
    end
  end

  scope :api do
    scope :v1 do
      use_doorkeeper do
        skip_controllers :authorizations, :applications, :authorized_applications
      end
    end
  end
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }

  # enum role: %i[user admin]

  def self.authenticate(email, password)
    author = Author.find_for_authentication(email:)
    author&.valid_password?(password) ? author : nil
  end

  def three_recent_posts
    posts.includes(%i[likes comments]).order('created_at DESC').first(3)
  end
end

app/controllers/api/v1/authors_controller.rb
class Api::V1::AuthorsController < Api::V1::ApplicationController
  skip_before_action :doorkeeper_authorize!, only: %i[create]

  def index
    authors = Author.all
    render json: authors
  end

  def show
    author = Author.find(params[:id])
    render json: author
  end

  def create
    author = Author.new(email: author_params[:email], password: author_params[:password], name: author_params[:name])

    client_app = Doorkeeper::Application.find_by(uid: params[:client_id])

    return render(json: { error: 'Invalid client ID' }, status: 403) unless client_app

    if author.save
      # create access token for the author, so the author won't need to login again after registration
      access_token = Doorkeeper::AccessToken.create(
        resource_owner_id: author.id,
        application_id: client_app.id,
        refresh_token: generate_refresh_token,
        expires_in: Doorkeeper.configuration.access_token_expires_in.to_i,
        scopes: ''
      )

      # return json containing access token and refresh token
      # so that author won't need to call login API right after registration
      render(json: {
               author: {
                 id: author.id,
                 email: author.email,
                 name: author.name,
                 access_token: access_token.token,
                 token_type: 'bearer',
                 expires_in: access_token.expires_in,
                 refresh_token: access_token.refresh_token,
                 created_at: access_token.created_at.to_time.to_i
               }
             })
    else
      render(json: { error: author.errors.full_messages }, status: 422)
    end
  end

  private

  def author_params
    params.permit(:email, :password, :name)
  end

  def generate_refresh_token
    loop do
      # generate a random token string and return it,
      # unless there is already another token with the same string
      token = SecureRandom.hex(32)
      break token unless Doorkeeper::AccessToken.exists?(refresh_token: token)
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/index.html.erb
<div class="author-list">
  <% @authors.includes([:posts]).each do |author| %>
    <%= link_to author_path(author), class: 'author-link' do %>
      <div class="author-card">    
        <img src=<%= author.photo %> />
        <div class = "author-details">
        
          <h2><%= author.name %></h2>
          
          <p>Number of posts: <%= author.posts.length %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/authors/show.html.erb
<div class="author-show">

  <div class="author-data">
    <img src=<%= @author.photo %> />
    <div class="portrait"></div>
    <div class="name-post">
      <h2><%= @author.name %></h2>
      <p>Posts: <%= @author.posts.length %></p>
    </div>
    <div class="author-bio">
      <h4>Bio</h4>
      <p> <%= @author.bio %> </p>
    </div>
  </div>
  
  <div class="author-recent-posts">
    <% if can? :create, @author.posts.build %>
      <%= render "posts/form" %>
    <% end %>
    <h3 class="recent-posts-title">Three most recent posts:</h3>
    <% @author.three_recent_posts.each do |post| %>
      <%= link_to author_post_path(@author, post) do %>
        <% render post %>
      <% end %>
    <% end %>
    <%= link_to '<button type="button">See All Posts</button>'.html_safe, author_posts_path(@author) %>
  </div>
</div>