config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  use_doorkeeper
  devise_for :authors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Sets the root page to be the login of devise
  devise_scope :author do
    root "devise/sessions#new"
  end
  
  resources :authors do
    resources :posts do
      resources :comments
      resources :likes, only: [:create, :destroy]
    end
  end

  
  # API ROUTES
  namespace :api do # /api
    namespace :v1 do # /api/v1
      resources :authors do # api/v1/users
        resources :posts, format: :json do # api/v1/users/:user_id/posts
          resources :comments, format: :json # api/v1/users/:user_id/posts/:post_id/comments
        end
      end
    end
  end

  scope :api do
    scope :v1 do
      use_doorkeeper do
        skip_controllers :authorizations, :applications, :authorized_applications
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  after_save :update_posts_counter

  belongs_to :author
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }
  validates :likes_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }

  def five_recent_comments
    comments.includes([:author]).order('created_at DESC').first(5)
  end

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  def index
    author = Author.find(params[:author_id])
    render json: author.posts
  end

  def show
    post = Post.find(params[:id])
    render json: post.comments
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @author = Author.find(params[:author_id])
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    post = Post.new(post_params)
    if post.save
      redirect_back_or_to author_path(current_author)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_back_or_to author_path(current_author), notice: 'Post was successfully deleted.' }
    end
  end

  private

  def post_params
    params
      .require(:post)
      .permit(:title, :text)
      .with_defaults(author_id: current_author.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: [ @author, @author.posts.build ], class: "post-form" do |form| %>
  <h3>New Post</h3>
  <%= form.label :title %>
  <%= form.text_field :title, placeholder: "Title", class: "post-input" %>
  <%= form.label :text %>
  <%= form.text_field :text, placeholder: "Text goes here", class: "post-input" %>
  <%= form.submit "Post", class: 'btn' %>
<% end %>

app/views/posts/_post.html.erb
<div class="post-card">
  <h3><%= post.title %></h3>
  <p><%= post.text %></p>
  <div class="likes-comments">
    <p><%= post.likes.length %> Likes</p>
    <p><%= post.comments.length %> Comments</p>
  </div>
  <div class="buttons-likes-comments">
    <% like = current_author.likes.find_by(post: post) %>
    <% if like.nil? %>
      <%= form_with model: @like, url: author_post_likes_path(@author, post), method: :post do |form| %>
        <%= form.submit "Like", class: "like" %>
      <% end %>
    <% else %>
      <%= form_with model: @like, url: author_post_like_path(@author, post, like), method: :delete do |form| %>
        <%= form.submit "Unlike", class: "like" %>
      <% end %>
    <% end %>
    <p>Comment</p>
  </div>
  <div class="comments-section">
    <% post.five_recent_comments.each do |comment| %>
      <%= render comment %>
    <% end %>
  </div>
  <% if can? :destroy, post %>
    <%= form_with model: post, url: author_post_path(post.author, post), method: :delete do |form| %>
      <%= form.submit "X", class: "btn delete-post" %>
    <% end %>
  <% end %>
  
</div>

app/views/posts/index.html.erb
<div class="author-show">

  <div class="author-data">
    <img src=<%= @author.photo %> />
    <div class="portrait"></div>
    <div class="name-post">
      <h2><%= @author.name %></h2>
      <p>Posts: <%= @author.posts.length %></p>
    </div>
    <div class="author-bio">
      <h4>Bio</h4>
      <p> <%= @author.bio %> </p>
    </div>
  </div>

  <div class="author-posts">
    <% if can? :create, @author.posts.build %>
      <%= render "posts/form" %>
    <% end %>
    <h3 class="all-posts-title">All posts:</h3>
    <% @author.posts.includes([:likes, :comments]).order("created_at DESC").each do |post| %>
      <%= link_to author_post_path(@author, post) do %>
        <%= render post %>
      <% end %>
    <% end %> 
  </div>
</div>

app/views/posts/show.html.erb
<div class="post">
  <h2><%= @post.title %></h2>
  <h5> by <%= @post.author.name %></h5>
  <p class="post-text"><%= @post.text %></p>
  <div class="likes-comments">
    <p><%= @post.likes.length %> Likes</p>
    <p><%= @post.comments.length %> Comments</p>
  </div>
  <div class="comments">
    <%= render @post.comments.includes([:author]) %>
  </div>

  <%= render "comments/form" %>

</div>